### PR TITLE
Pull the Hadoop version from the environment.

### PR DESCRIPTION
**Pull request by sarahgerweck**
This introduces two environment variables that you can use to control
the version of Hadoop that you build against. The Spark project
uses `SPARK_HADOOP_VERSION`, which is supported. By analogy, we
also support `SHARK_HADOOP_VERSION`, which has precedence over
`SPARK_HADOOP_VERSION`. If neither of these environment variables are
set at build time, the defaults from the build script are used.

The algorithm looks like this:
1. Use `SHARK_HADOOP_VERSION` if set.
2. Use `SPARK_HADOOP_VERSION` if set.
3. Use the default that is hard-coded into the build definition.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by sarahgerweck** [comment]
You don't need anything from me for this do you? The change is very conservative.

**Comment by rxin** [comment]
Yea - the changes look good. I was waiting for Jenkins to respond but something is wrong with it.

**Comment by sarahgerweck** [comment]
Cool, just making sure. :-)

**Pull request merged**
