### PR TITLE
Removed hadoop-test-0.20.2.jar from the bin/dev/test

### PR DESCRIPTION
**Pull request by dosoft**
as described - removed obsolete hadoop-test-0.20.2.jar from the bin/dev/test

### CODE REVIEW

**Comment by harveyfeng** [comment]
Jenkins test this please

**Comment by harveyfeng** [comment]
That worked last time...

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
I also cherry picked it into branch-0.9.

**Pull request merged**
