### PR TITLE
Bug fix: RLDecoder.hasNext may lose duplicated values

### PR DESCRIPTION
**Pull request by liancheng**
When the last several elements of some column are duplicated, `RLDecoder.hasNext` only returns `true` for the first one and loses all those duplicated values.

### CODE REVIEW

**Comment by liancheng** [comment]
@rxin Please have a look?

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by rxin** [comment]
LGTM provided Jenkins is happy.

**Comment by rxin** [comment]
Thanks!

**Pull request merged**
