### PR TITLE
Join optimization: rewrite a pattern match into if/else.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by aarondav** [comment]
According to this, pattern matches should be if/elses: http://stackoverflow.com/questions/754166/how-is-pattern-matching-in-scala-implemented-at-the-bytecode-level

Is this not happening, or is there another reason this pattern is better?

**Comment by rxin** [comment]
It only works if those are literals. Take a look at this program:

``` scala

  val ONE = 1
  val TWO = 2
  val THREE = 3


  def test(v: Int): Int = {
    (v: @switch) match {
      case ONE =>
        1 + 1
      case TWO =>
        2 + 1
      case THREE =>
        3 + 1
      case _ =>
        5
    }
  }
```

The -print generated code is:

``` scala
    private[this] val ONE: Int = _;
    <stable> <accessor> def ONE(): Int = Test.this.ONE;
    private[this] val TWO: Int = _;
    <stable> <accessor> def TWO(): Int = Test.this.TWO;
    private[this] val THREE: Int = _;
    <stable> <accessor> def THREE(): Int = Test.this.THREE;
    def test(v: Int): Int = {
      case <synthetic> val x1: Int = (v: Int);
      case7(){
        if (Test.this.ONE().==(x1))
          matchEnd6(2)
        else
          case8()
      };
      case8(){
        if (Test.this.TWO().==(x1))
          matchEnd6(3)
        else
          case9()
      };
      case9(){
        if (Test.this.THREE().==(x1))
          matchEnd6(4)
        else
          case10()
      };
      case10(){
        matchEnd6(5)
      };
      matchEnd6(x: Int){
        x
      }
    };
    def <init>(): Test.type = {
      Test.super.<init>();
      Test.this.ONE = 1;
      Test.this.TWO = 2;
      Test.this.THREE = 3;
      ()
    }
  }
```

**Comment by rxin** [comment]
Actually my bad. The Scala print output is deceiving. I looked at the generated byte code and there is no "function calls". This PR is not needed.

```
  public int test(int);
    Code:
       0: iload_1       
       1: istore_2      
       2: aload_0       
       3: getfield      #66                 // Field ONE:I
       6: iload_2       
       7: if_icmpne     15
      10: iconst_2      
      11: istore_3      
      12: goto          43
      15: aload_0       
      16: getfield      #68                 // Field TWO:I
      19: iload_2       
      20: if_icmpne     28
      23: iconst_3      
      24: istore_3      
      25: goto          43
      28: aload_0       
      29: getfield      #70                 // Field THREE:I
      32: iload_2       
      33: if_icmpne     41
      36: iconst_4      
      37: istore_3      
      38: goto          43
      41: iconst_5      
      42: istore_3      
      43: iload_3       
      44: ireturn       

```

**Comment by rxin** [comment]
@marmbrus - I gave you the wrong information about pattern matching previously!

**Pull request closed without merging**
