### PR TITLE
Null mergeCombiners will cause NPE in ExternalAppendOnlyMap

### PR DESCRIPTION
**Pull request by tianyi**
in most time , null mergeCombiners works fine if each key is different
from others, but if some key are duplicate , it will cause NPE when the
function mergeIfKeyExists is called in ExternalAppendOnlyMap.scala

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Looks like there's an error in the code that it wouldn't compile. Do you mind updating it?

**Comment by tianyi** [comment]
Done , Sorry for the mistake.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by rxin** [comment]
Thanks! Merging this now.

**Pull request merged**
