### PR TITLE
 Handle database namespaces for cached tables

### PR DESCRIPTION
**Pull request by sundeepn**
Cached tables currently ignore database name which makes caching buggy for users using multiple databases.
Enhanced the memoryMetadataManager to require database name inaddition to the tablename for all metadata operations.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks, Sundeep. This part of the  codebase is undergoing pretty big changes by Harvey right now. I will ask Harvey to merge your changes into Shark as part of his partition cached table change. 

@harveyfeng

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by harveyfeng** [comment]
Cherry-picked commit 8920903 into master. It seems like 2844c67 is a duplicate of https://github.com/amplab/shark/pull/186, so I didn't merge that one yet.

**Comment by sundeepn** [comment]
All this functionality is now in the master. Closing this request.

**Pull request closed without merging**
