### PR TITLE
Upgrade to scala 2.10

### PR DESCRIPTION
**Pull request by marmbrus**
- Replace ClassManifests with ClassTags
- Denote use of language features (implicits, existencials)
- Stop using deprecated ConcurrentMap and spawn.
- Stop using deprecated spark setJobDescription.
- Avoid catching all Throwables in favor of catching Exception.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks @marmbrus. Do you mind updating the run-tests-from-scratch-workspace script so Jenkins can verify the tests?

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by andyk** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
test this please

**Comment by marmbrus** [comment]
test this please

**Comment by marmbrus** [comment]
test this please

**Comment by marmbrus** [comment]
test this please

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
test this please

**Comment by rxin** [comment]
Thanks!

**Pull request merged**
