### PR TITLE
scalastyle checks for sbt. All warnings for now. Execute using 'sbt scal...

### PR DESCRIPTION
**Pull request by junkumar**
...astyle'

Reynold, take a look and see if these simple checks for you. They include 100 columns per line, braces, whitespace etc..

### CODE REVIEW

**Comment by rxin** [comment]
Thanks - I will give it a try.

**Comment by rxin** [comment]
Do you know if there is a way to put the scalastyle config file in a different folder (not at top level)?

**Comment by rxin** [comment]
The other thing we should disable is the cyclomatic complexity check. If you write a case match with more than 9 cases, that would trigger it. I am not sure if we want that.

**Comment by rxin** [comment]
FYI I submitted this pull request to scalastyle: https://github.com/scalastyle/scalastyle/pull/67/files

**Comment by junkumar** [comment]
While we are waiting for the long import lines fix. I think we should go ahead and merge these fixes/config/code.

Also, the effort spent fixing the current style issues will be of no use if the shark source keeps moving forward. The merge will get harder with more commits.

**Comment by rxin** [comment]
Hi Nandu,

I just cherry picked your build/scalastyle changes into master. I didn't merge in the scala style cleanup yet, because that would make it very hard to merge Harvey's changes needed for partitioned cache tables (for 0.8.1). We will do that after Harvey's changes are in.

**Comment by rxin** [comment]
Nandu, I updated this PR manually and created it here: https://github.com/amplab/shark/pull/205

**Comment by junkumar** [comment]
Cool. I am going to close this one because you merged this code through #205.

**Pull request closed without merging**
