### PR TITLE
Java API

### PR DESCRIPTION
**Pull request by JoshRosen**
This pull request adds a basic Java API to Shark ([SHARK-115](https://spark-project.atlassian.net/browse/SHARK-115)).  The implementation is essentially a pair of thin wrappers around `SharkContext` and `TabledRDD` to implement the `JavaSparkContext` and `JavaRDDLike` APIs.

### CODE REVIEW

**Comment by rxin** [comment]
I merged this manually because there were some test failures caused by data warehouse location set twice (once by JavaAPISuite and once by SQLSuite). Thanks, Josh!

**Comment by pwendell** [comment]
This is really cool - nice work Josh!

**Comment by andrewmilkowski** [comment]
great work, thank you, I will be trying it soon, have spark/hadoop/hive/tachyon env running on mesos, and now will be able to add shark to the equation

**Comment by andrewmilkowski** [comment]
Mesos and JavaSharkContext don't play nice with each other (but maybe it is just mesos and spark)

https://groups.google.com/d/msg/shark-users/4OvK8Ux1I4Q/LcJvfw5OUmkJ

**Comment by rxin** [comment]
Do you know if this works in the Scala API?

**Comment by andrewmilkowski** [comment]
(no I don't) can certainly try need to quickly port it...

**Comment by andrewmilkowski** [comment]
same error... with sample code below (spark direct works)

object TestJob extends App {

   val executorEnvVars = Map[String, String]()

  //val master = "spark://localhost.localdomain:7077"
  val master = "mesos://localhost.localdomain:5050"
  val jobName = "Test Job with Shark Query"

  val sc = new SharkContext(master, jobName, null, Nil, executorEnvVars)

  SharkEnv.sc = sc;

  System.setProperty("spark.serializer", classOf[spark.KryoSerializer].getName)
  System.setProperty("spark.kryo.registrator", classOf[shark.KryoRegistrator].getName)

  sc.sql2console("SELECT COUNT(1) FROM test_log")

}

**Pull request merged**
