### PR TITLE
Migrating to Hive 0.9.0

### PR DESCRIPTION
**Pull request by dennybritz**
- A couple of minor changes in package/class naming
- SerDe Stats does not collect any actual stats yet. This is a TODO.
- ExplainWork formatted (JSON) output disabled by constructor
- Fixes #24

### CODE REVIEW

**Comment by rrmckinley** [comment]
Do you have time to refactor SharkDriver.scala to use the getHooks method for saHooksMethod on line 68? I've tried the following, but I don't know enough Scala to make it work when it is actually invoked.

``` scala

val saHooksMethod = this.getClass.getSuperclass.getDeclaredMethod(
    "getHooks", classOf[HiveConf.ConfVars], classOf[Class[_]])
...
// Throws an error:
val saHooks = saHooksMethod.invoke(HiveConf.ConfVars.SEMANTIC_ANALYZER_HOOK,
  classOf[AbstractSemanticAnalyzerHook]).asInstanceOf[JavaList[AbstractSemanticAnalyzerHook]]

```

**Comment by dennybritz** [comment]
I added it. Your code is basically correct, but the first argument to the `invoke` method has to be the calling instance, you forgot that argument.

**Comment by rrmckinley** [comment]
I see that I refactored 'this' right out :) Thanks for your help!

**Comment by rrmckinley** [comment]
Also, have you tried your Shark branch with the dev branch of Spark (0.6.0-SNAPSHOT)? I've refactored your branch a bit to use ByteBuffer on various interfaces. That seemed to go fine. However, I can't get the RDDSuite.scala test to pass in Mesos. It complains of not being able to deserialize scala.Tuple2 and SharkDriver not having a constructor that takes scala.Tuple2. Do you have any ideas what might be going on?

**Comment by dennybritz** [comment]
I haven't tried the dev branch yet. If you can wait for a day then I'll look into it tomorrow.

**Comment by dennybritz** [comment]
I just tried the dev branch of Spark and the tests are passing fine for me. I changed about 4 places to make use of ByteBuffer's `array` and `wrap` methods. This probably belongs into a different pull-request / topic though.

**Comment by rrmckinley** [comment]
I was able to get tests to pass the same way. But, then there is that test instruction on the readme. export TEST=down... Did you happen to test that?

**Comment by rrmckinley** [comment]
I should mention that the specific test I got stopped on was RDDSuite as mentioned in https://github.com/amplab/shark/wiki/Developer-Guide#Testing. Thanks

**Comment by rxin** [comment]
Denny - do you mind updating the JDBC part as well? (The one submitted by Ram)

rrmckinley - which test failed exactly?

**Comment by rxin** [comment]
Closing this one.

#54 is the new issue for upgrading to Hive 0.9.

**Pull request closed without merging**
