### PR TITLE
Bug fix for NULL data in table when using sql2rdd/TableRDD (SHARK-119)

### PR DESCRIPTION
**Pull request by jhartlaub**
Data returned as java objects or "null" values- previously the Scala objects could not represent "null".

### CODE REVIEW

**Comment by rxin** [comment]
Thanks, Jon. These looks good. Can you limit the line width to 100 characters?

**Comment by jhartlaub** [comment]
will do - will add some unit tests too

**Comment by rxin** [comment]
Jon, let me know if you want me to merge this in.

**Comment by jhartlaub** [comment]
Hey Reynold, we've been using this for quite a while now- I think it is good to go.

**Comment by rxin** [comment]
Thanks!

**Pull request merged**
