### PR TITLE
FileAlreadyExistException when writing tachyon table

### PR DESCRIPTION
**Pull request by shimingfei**
currently Shark write data into Tachyon table directly by RAWTable interface in Tachyon.
when  speculation execution is on,   it throws FileAlreadyExistException because two tasks attempts to write same partition into Tachyon table
the approach to solve the problem is first write output of each task into a temp folder,  then commit the result when the task ends. just like write to HDFS.

### CODE REVIEW

**Comment by GraceH** [comment]
yes. This fix is quite important in the speculative run. Otherwise, 2 conflict writes are working on the same target. any idea?

**Comment by haoyuan** [comment]
@aarondav can you take a look at this?

**Comment by haoyuan** [comment]
@aarondav , @rxin did this at. :)

**Comment by aarondav** [comment]
LGTM, @rxin please merge!

**Pull request merged**
