### PR TITLE
Maven POM file for Shark, Debian packaging, and "run" script improvement

### PR DESCRIPTION
**Pull request by mbautin**
- Adding a POM file for building with Maven, both with Hadoop 1 and Hadoop 2
- Adding Debian packaging
- Updating the run script to be able to run with a fat jar (no Scala
  dependency).

### CODE REVIEW

**Comment by rxin** [comment]
Thanks for submitting this. Just want to drop a note saying we haven't been ignoring you. I am waiting for @massie to take a look, since he is our in-house Maven guru now :)

**Comment by massie** [comment]
I'm seeing the following warning when I do a `mvn clean install`....

[WARNING] Some problems were encountered while building the effective model for edu.berkeley.cs.amplab:shark_2.9.2:jar:0.2
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 146, column 15
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 158, column 15
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.

The pom.xml needs to be cleaned up a little.

**Comment by mbautin** [comment]
Matt: I've specified plugin version and replaced ${version} with ${hive.version} (thanks for pointing out this bug), and the Maven error messages do not show up anymore.

**Comment by mbautin** [comment]
@massie @rxin any update on this? Should I re-submit this against Shark trunk?

**Comment by massie** [comment]
Thanks for adding explicit version numbers.  The error messages are gone.

When I try to run `mvn clean install`, I get the following error message:

[ERROR] Failed to execute goal on project shark_2.9.2: Could not resolve dependencies for project edu.berkeley.cs.amplab:shark_2.9.2:jar:0.2: The following artifacts could not be resolved: org.apache.hive:hive-common:jar:0.9.0-shark, org.apache.hive:hive-exec:jar:0.9.0-shark, org.apache.hive:hive-cli:jar:0.9.0-shark, org.apache.hive:hive-serde:jar:0.9.0-shark, org.apache.hive:hive-metastore:jar:0.9.0-shark, org.apache.hive:hive-service:jar:0.9.0-shark, org.apache.hive:hive-hbase-handler:jar:0.9.0-shark, org.apache.hive:hive-exec-test:jar:0.9.0-shark: Failure to find org.apache.hive:hive-common:jar:0.9.0-shark in http://repo.typesafe.com/typesafe/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of TypesafeRepository has elapsed or updates are forced -> [Help 1]

which means that maven isn't able to find the hive jars.

The hive.dev.home property seems to imply that the hive dependencies will be read with scope=system?

What am I missing here?

**Comment by mbautin** [comment]
@massie: the maven script currently relies on a Shark-patched version of Hive being available in the local Maven repository. To build against a different version of Hive, one needs to specify e.g. `-Dhive.version=0.9.0`. Alternatively, to build Hive with a custom version number and publish artifacts locally you could run something like 

```
ant clean
ant -Dversion=0.9.0-shark package
ant -Dversion=0.9.0-shark -Dmvn.publish.repo=local maven-build
ant -Dversion=0.9.0-shark -Dmvn.publish.repo=local maven-publish
```

in the Hive directory.

Do you think it is better to default to a different Hive version number, e.g. 0.9.0? In that case people will be able to build out of the box but may be missing important Hive patches required by Shark. Or would a better approach be to publish the patched 0.9.0-shark artifacts somewhere?

**Comment by mbautin** [comment]
Opened a new pull request, https://github.com/amplab/shark/pull/83, against the master branch. Closing this one, and we can back-port these changes to 0.6.1 when they get committed into master.

**Pull request closed without merging**
