### PR TITLE
Exclude more libs from tachyon

### PR DESCRIPTION
**Pull request by haoyuan**

### CODE REVIEW

**Comment by rxin** [comment]
HY this is failing. Can you take a look?

**Comment by haoyuan** [comment]
It fails because of "
./bin/dev/run-tests-from-scratch: line 254: sbt/sbt: No such file or directory
Build step 'Execute shell' marked build as failure
".

Same message as the Master branch.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Thanks.

**Pull request merged**
