### PR TITLE
Update Shark build file now that hadoop agnostic build update has been merged into Spark master

### PR DESCRIPTION
**Pull request by andyk**
Update bin/dev/run-tests-from-scratch now that Hadoop agnostic builds -- i.e. https://github.com/mesos/spark/pull/838 -- have been merged into Spark master.

### CODE REVIEW

**Comment by andyk** [comment]
The Shark build is failing after mesos/spark#838 was merged and I believe this should fix it.

**Comment by andyk** [comment]
See https://amplab.cs.berkeley.edu/jenkins/job/Shark-Master-Hadoop1/130/ for the failing build.

**Comment by andyk** [comment]
jenkins test this please

**Comment by rxin** [comment]
Andy, why are we changing the hadoop version from 0.20.205.0 to 1.2?

**Comment by mateiz** [comment]
0.20.205 doesn't have hadoop-client. You need 1.0.1 or better for that -- see http://mvnrepository.com/artifact/org.apache.hadoop/hadoop-client

**Comment by mateiz** [comment]
BTW right now Spark uses 1.2.1, but we may switch it back to 1.0.4, so it might be good to do that here too.

**Comment by rxin** [comment]
Jenkins, test this again please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by andyk** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Merging this first and we will fix the other 5 failing tests later, since they were already failing. Thanks, Andy!

**Pull request merged**
