### PR TITLE
Fixed testCliDriver_exim_* tests (check local Path before using)

### PR DESCRIPTION
**Pull request by dosoft**
Seems like Shark doesn't check paths before using. It causes failures for the following tests:

testCliDriver_exim_11_managed_external
testCliDriver_exim_12_external_location
testCliDriver_exim_13_managed_location
testCliDriver_exim_14_managed_location_over_existing
testCliDriver_exim_16_part_external
testCliDriver_exim_19_00_part_external_location
testCliDriver_exim_19_part_external_location
testCliDriver_exim_20_part_managed_location

These tests reproduce the scenario, when 'data' directory is deleted but metadata is not. Hive handles this scenario correctly and 'select *' returns an empty rowset, but shark throws an exception.

### CODE REVIEW

**Comment by harveyfeng** [comment]
Thanks! Could you also update tests_pass.txt?

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by harveyfeng** [comment]
Jenkins, retest this please

**Comment by harveyfeng** [comment]
Jenkins, retest this please

**Comment by harveyfeng** [comment]
ping @rxin

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Pull request merged**
