### PR TITLE
push down the column pruner to HBase.

### PR DESCRIPTION
**Pull request by plusplusjiajia**
get the column ids that are referenced in the Query, and push down the column pruner to HBase.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
@plusplusjiajia do you mind submitting a new pull request against the master branch instead of hive0.11 branch? The hive0.11 branch has been merged into master.

**Comment by plusplusjiajia** [comment]
@rxin I found the "Add support for PPD with ORCfile in Shark" patch by ybyudin in master branch has been supported this feature, so this pull request is not needed now.

**Comment by rxin** [comment]
Ok thanks. Closing this one then.

**Pull request closed without merging**
